Repository checkmarx-ltd/cx-common-js-client, pull requests merged in 2020-06, with the labels that each got.

#12 Add release-drafter github action to automatically generate release notes.
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#17 Feature/new sca integration
  package-lock.json
  package.json
  src/dto/api/armStatus.ts
  src/dto/api/policyViolationGroup.ts
  src/dto/api/reportStatus.ts
  src/dto/api/scanStatus.ts
  src/dto/api/scanStatusResponse.ts
  src/dto/api/updateScanSettingsRequest.ts
  src/dto/project.ts
  src/dto/sastConfig.ts
  src/dto/sca/clientType.ts
  src/dto/sca/project.ts
  src/dto/sca/remoteRepositoryInfo.ts
  src/dto/sca/report/cveReportTableRow.ts
  src/dto/sca/report/dependencyPathSegment.ts
  src/dto/sca/report/finding.ts
  src/dto/sca/report/package.ts
  src/dto/sca/report/packageSeverity.ts
  src/dto/sca/report/packageUsage.ts
  src/dto/sca/report/scaSummaryResults.ts
  src/dto/sca/report/severity.ts
  src/dto/sca/scaConfig.ts
  src/dto/sca/scaLoginSettings.ts
  src/dto/sca/scaReportResults.ts
  src/dto/sca/scaResults.ts
  src/dto/sca/scanInfoResponse.ts
  src/dto/sca/scanStatus.ts
  src/dto/sca/sourceLocationType.ts
  src/dto/scaConfig.ts
  src/dto/scaLoginSettings.ts
  src/dto/scaResults.ts
  src/dto/scaSummaryResults.ts
  src/dto/scanConfig.ts
  src/dto/scanResults.ts
  src/dto/scanSummary.ts
  src/index.ts
  src/services/clients/armClient.ts
  src/services/clients/cxClient.ts
  src/services/clients/httpClient.ts
  src/services/clients/reportingClient.ts
  src/services/clients/sastClient.ts
  src/services/clients/scaClient.ts
  src/services/clients/teamApiClient.ts
  src/services/sastSummaryEvaluator.ts
  src/services/scaSummaryEvaluator.ts
  src/services/scaWaiter.ts
  src/services/scanSummaryEvaluator.ts
  src/services/waiter.ts
  src/services/zipper.ts
  tests/filePathFilter.test.ts
  tests/scaScanSummary.test.ts
  tests/scanSummaryEvaluator.test.ts
  tests/utils.ts
Labels: size/XXL

#18 Delete deploy-docker.yml file
  .github/workflows/deploy-docker.yml
  package-lock.json
  package.json
Labels: size/S

#19 Delete files
  .github/dependabot.yml
  .github/workflows/cx-osa-scan.yml
  .github/workflows/cx-sast-scan.yml
  .github/workflows/cx-sca-scan.yml
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
Labels: size/L

#22 Update dependency version to resolve OSA high vul.
  package-lock.json
  package.json
Labels: size/XS
