Repository checkmarx-ltd/cx-common-js-client, pull requests merged in 2021-09, with the labels that each got.

#56 Avoid publishing for other branches
  azure-pipelines.yml
Labels: size/XS

#57 Avoid npm publish for other branches
  azure-pipelines.yml
Labels: size/XS

#50 Fixed regression due to some package upgrades
  package.json
  src/dto/sastConfig.ts
  src/dto/sca/scaConfig.ts
  src/services/clients/cxClient.ts
Labels: size/S

#59 Added code changes for Engine Config support
  src/dto/sastConfig.ts
  src/services/clients/cxClient.ts
Labels: size/XS

#60 Changes for superagent and archiver downgrade
  package.json
Labels: size/XS

#61 Post scan action id support
  package.json
  src/dto/sastConfig.ts
  src/services/clients/cxClient.ts
  src/services/clients/httpClient.ts
  src/services/clients/sastClient.ts
Labels: size/L
