Repository checkmarx-ltd/cx-common-js-client, pull requests merged in 2021-08, with the labels that each got.

#51 Committing SSO support changes to common js client
  src/dto/apiConstant.ts
  src/dto/authSSODetails.ts
  src/index.ts
  src/services/clients/httpClient.ts
Labels: size/L

#53 Added new API call to update existing fields in SAST DB. The call is …
  src/services/clients/httpClient.ts
Labels: size/XS

#54 Ssl cert support
  package.json
  src/services/clients/httpClient.ts
Labels: size/M
