Repository checkmarx-ltd/cx-common-js-client, pull requests merged in 2023-04, with the labels that each got.

#90 Ado plugin sent to scan api if cannot reach swagger
  src/services/clients/cxClient.ts
Labels: size/M

#89 Sca scan timeout and SAST scan cancellation from server and fixing of incorrect incremental and vulnerability threshold logs
  src/dto/sca/scaConfig.ts
  src/services/clients/sastClient.ts
  src/services/clients/scaClient.ts
  src/services/scaWaiter.ts
Labels: size/M

#93 Integration branch q1
  package.json
  src/dto/sca/scaConfig.ts
  src/services/clients/cxClient.ts
  src/services/clients/sastClient.ts
  src/services/clients/scaClient.ts
  src/services/scaWaiter.ts
Labels: size/L

#94 Integration branch q1
  package.json
  src/services/clients/sastClient.ts
  src/services/clients/scaClient.ts
Labels: size/S

#95 Updated Proxy-agent version to 4.0.1
  package.json
Labels: size/XS
